apiVersion: network.kubesphere.io/v1alpha2
kind: Eip
metadata:
    name: eip-pool
    annotations:
      eip.openelb.kubesphere.io/is-default-eip: "true"
spec:
    address: 192.168.26.30-192.168.26.50
    priority: 100
    namespaceSelector:
      kubesphere.io/workspace: workspace
    disable: false
    protocol: layer2
    interface: ens33