apiVersion: v1
kind: Service
metadata:
  name: nginx-test
  namespace: custom-food-menu
  labels:
    app: nginx-test
  # annotations:
  #  lb.kubesphere.io/v1alpha1: openelb
  #  eip.openelb.kubesphere.io/v1alpha2: eip-pool
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: nginx-eip-test