apiVersion: v1
kind: Service
metadata:
  name: nginx-test
  namespace: custom-food-menu
  labels:
    app: nginx-test
  annotations:
    eip.openelb.kubesphere.io/is-default-eip: "true"
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: nginx-eip-test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-eip-test
  namespace: custom-food-menu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-eip-test  # 必须与 Pod template 的 labels 一致
  template:
    metadata:
      labels:
        app: nginx-eip-test  # 关键：Service 的 selector 匹配此标签
    spec:
      containers:
      - name: nginx
        image: 192.168.26.99/custom_food_menu/nginx:1.28
        ports:
        - name: http      # 显式命名端口（可选，与 Service 的 targetPort 对应）
          containerPort: 80  # 必须与 Service 的 targetPort 一致
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
        readinessProbe:   # 添加健康检查（修复 Endpoints 问题的关键！）
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5