apiVersion: v1
kind: Service
metadata:
  name: test-svc
  namespace: custom-food-menu
  labels:
    app: test-svc
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80 
  selector:
    app: test-svc